spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flowableDB
    username: postgres
    password: postgres
  application:
    name: flowable-bpm-test

flowable:
  auto-deployment:
    use-lock: true # default is off
    lock-wait-time: 5m # default
